import type { EvidenceEffect } from '@/types/medical';

export const evidenceEffects: EvidenceEffect[] = [
  {
    id: 'structured-exercise-sbp',
    scenarioId: 'structured_exercise',
    label: 'Structured exercise reduces systolic blood pressure',
    biomarker: 'systolicBloodPressure',
    deltaType: 'absolute',
    delta: -4.15,
    unit: 'mmHg',
    confidence: 'high',
    useInRiskScore: true,
    timeHorizon: 'around 8-12 weeks',
    source: 'Meta-analysis on aerobic/resistance exercise and blood pressure',
    note: 'SBP is a direct input to cardiovascular risk calculators.'
  },
  {
    id: 'structured-exercise-tc',
    scenarioId: 'structured_exercise',
    label: 'Structured exercise reduces total cholesterol',
    biomarker: 'totalCholesterol',
    deltaType: 'absolute',
    delta: -5.9,
    unit: 'mg/dL',
    confidence: 'high',
    useInRiskScore: true,
    timeHorizon: 'around 12 weeks',
    source: 'Smart et al., 2024 exercise training and blood lipids meta-analysis',
    note: 'Total cholesterol is a direct input to ASCVD / Framingham-style calculators.'
  },
  {
    id: 'structured-exercise-hdl',
    scenarioId: 'structured_exercise',
    label: 'Structured exercise increases HDL cholesterol',
    biomarker: 'hdlCholesterol',
    deltaType: 'absolute',
    delta: 2.11,
    unit: 'mg/dL',
    confidence: 'high',
    useInRiskScore: true,
    timeHorizon: 'around 12 weeks',
    source: 'Smart et al., 2024 exercise training and blood lipids meta-analysis',
    note: 'HDL cholesterol is a direct input to ASCVD / Framingham-style calculators.'
  },
  {
    id: 'exercise-bmi',
    scenarioId: 'structured_exercise',
    label: 'Exercise program reduces BMI',
    biomarker: 'bmi',
    deltaType: 'absolute',
    delta: -0.68,
    unit: 'kg/m2',
    confidence: 'medium',
    useInRiskScore: false,
    timeHorizon: 'around 12 weeks',
    source: 'PLOS One meta-analysis of aerobic and resistance exercise on BMI',
    note: 'Secondary display metric only. Do not use as main risk driver unless the chosen calculator uses BMI.'
  },
  {
    id: 'sleep-sbp',
    scenarioId: 'sleep_improvement',
    label: 'Sleep improvement reduces systolic blood pressure in short sleepers',
    biomarker: 'systolicBloodPressure',
    deltaType: 'absolute',
    delta: -5,
    unit: 'mmHg',
    confidence: 'medium',
    useInRiskScore: true,
    timeHorizon: 'around 3-16 weeks depending on intervention',
    appliesIf: 'sleepHours < 7',
    source: 'Sleep intervention meta-analysis on cardiovascular risk',
    note: 'Apply only for short sleepers. Do not modify HDL, LDL, or total cholesterol from sleep in the MVP.'
  },
  {
    id: 'sleep-energy-intake',
    scenarioId: 'sleep_improvement',
    label: 'Sleep extension reduces energy intake',
    biomarker: 'energyIntake',
    deltaType: 'absolute',
    delta: -270,
    unit: 'kcal/day',
    confidence: 'medium',
    useInRiskScore: false,
    timeHorizon: 'around 2 weeks in the cited RCT',
    appliesIf: 'sleepHours < 6.5',
    source: 'Tasali et al., 2022 sleep extension RCT',
    note: 'Secondary trajectory only. Do not instantly reduce BMI from this. If implemented, convert gradually through energy balance.'
  },
  {
    id: 'mbsr-sbp',
    scenarioId: 'stress_reduction',
    label: 'MBSR reduces systolic blood pressure',
    biomarker: 'systolicBloodPressure',
    deltaType: 'absolute',
    delta: -6.64,
    unit: 'mmHg',
    confidence: 'high',
    useInRiskScore: true,
    timeHorizon: 'around 8 weeks',
    source: 'Hypertension, AHA Journal, 2020 meta-analysis of 12 RCTs',
    note: 'Use for an 8-week mindfulness-based stress reduction intervention, not for generic stress claims.'
  },
  {
    id: 'stop-smoking',
    scenarioId: 'stop_smoking',
    label: 'Smoking cessation changes smoking status',
    biomarker: 'smoker',
    deltaType: 'boolean',
    delta: false,
    confidence: 'high',
    useInRiskScore: true,
    timeHorizon: 'status change immediate, health benefit progressive',
    source: 'ASCVD / Framingham smoking input and prevention guidelines',
    note: 'Smoking is a direct categorical input in cardiovascular risk calculators.'
  }
];
